In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import  numpy as np
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/Dataset/news.csv")
data

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 4 columns]

In [3]:
df=pd.DataFrame(data)
y= df['label']
y

0       FAKE
1       FAKE
2       REAL
3       FAKE
4       REAL
        ... 
6330    REAL
6331    FAKE
6332    FAKE
6333    REAL
6334    REAL
Name: label, Length: 6335, dtype: object

In [4]:
df =df.drop(['label','Unnamed: 0','title'],axis=1)
x=df
x

text
0     Daniel Greenfield, a Shillman Journalism Fello...
1     Google Pinterest Digg Linkedin Reddit Stumbleu...
2     U.S. Secretary of State John F. Kerry said Mon...
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...
4     It's primary day in New York and front-runners...
...                                                 ...
6330  The State Department told the Republican Natio...
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332   Anti-Trump Protesters Are Tools of the Oligar...
6333  ADDIS ABABA, Ethiopia —President Obama convene...
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...

[6335 rows x 1 columns]

In [5]:
from sklearn.metrics import accuracy_score,classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
X_train_new=cv.fit_transform(X_train['text'])
X_test_new = cv.transform(X_test['text'])

print(cv.get_feature_names())
print(np.shape(cv.get_feature_names()))
print(X_train_new.toarray())
np.shape(X_train_new.toarray())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['00', '000', '0000', '00000031', '000035', '0001pt', '0002', '000billion', '000ft', '000km', '000x', '001', '0011', '003', '004', '004s', '005', '005s', '006', '00684', '006s', '007s', '008', '008s', '009', '0099', '00am', '00pm', '01', '011', '012', '013', '013c2812c9', '014', '015', '016', '018', '01am', '02', '022', '023', '024', '027', '02714', '028', '02870', '03', '031', '032', '0325', '033', '035', '037', '03747', '03eb', '04', '040', '0400', '042', '047', '048', '049', '05', '050', '0509245d29', '052', '053', '056', '06', '062', '063', '0640', '066', '068', '07', '0700', '071', '075', '0750', '076', '079', '07dryempjx', '08', '081', '082', '084', '0843', '085', '0851', '089', '0891', '09', '091', '093', '098263', '09am', '09pm', '0_65b67362bd', '0_jgdktlmn', '0_kvyhphja', '0a_merrill', '0b6njlny5j', '0d', '0dpbdk6rjd', '0fjjvowyhg8qtskiz', '0h4at2yetra17uxetni02ls2jeg0mty45jrcu7mrzsrpcbq464i', '0hour', '0hq3vb2giv', '0in', '0jsn6pjkan', '0pt', '0t5', '0txrbwvobzz4fi5nksw6k5a6c

(5068, 62518)

In [6]:
pac = PassiveAggressiveClassifier(max_iter=50)
pac.fit(X_train_new,y_train)
y_pred = pac.predict(X_test_new)
print("Predicted value is \n",y_pred)
print("Real value is \n",y_test)

Predicted value is 
 ['REAL' 'REAL' 'REAL' ... 'FAKE' 'REAL' 'FAKE']
Real value is 
 954     REAL
2377    REAL
1174    REAL
2669    FAKE
1942    FAKE
        ... 
2481    FAKE
1421    FAKE
5880    FAKE
1384    REAL
958     FAKE
Name: label, Length: 1267, dtype: object


In [7]:
accuracy_score(y_test,y_pred)

0.9108129439621152

In [8]:
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
sw=stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [9]:
rev1 = []
for i in range(0,6335):
  new = re.sub('[^a-zA-Z]',' ',data['title'][i])
  new = new.lower()
  new = new.split()
  new = [ps.stem(word) for word in new if not word in set(sw)]
  new =  ' '.join(new)
  rev1.append(new)
rev1

['smell hillari fear',
 'watch exact moment paul ryan commit polit suicid trump ralli video',
 'kerri go pari gestur sympathi',
 'berni support twitter erupt anger dnc tri warn',
 'battl new york primari matter',
 'tehran usa',
 'girl horrifi watch boyfriend left facetim',
 'britain schindler die',
 'fact check trump clinton command chief forum',
 'iran reportedli make new push uranium concess nuclear talk',
 'three clinton iowa glimps fire elud hillari clinton campaign',
 'donald trump shockingli weak deleg game somehow got even wors',
 'strong solar storm tech risk today news oct video',
 'way america prepar world war',
 'trump take cruz lightli',
 'women lead differ',
 'shock michel obama hillari caught glamor date rape promot',
 'hillari clinton huge troubl america notic sick thing hidden pictur liberti writer news',
 'iran bill obama like',
 'chart explain everyth need know partisanship america',
 'slipperi slope trump propos ban muslim',
 'episod sunday wire hail deplor special g

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [12]:
voc_size = 6000
onehot_repr=[one_hot(words,voc_size)for words in rev1]
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
np.shape(embedded_docs)

[[   0    0    0 ... 2675 5727 3235]
 [   0    0    0 ... 2200 2340 4946]
 [   0    0    0 ...  175 4867 2171]
 ...
 [   0    0    0 ... 5295 4511 2671]
 [   0    0    0 ... 2475 3864 5081]
 [   0    0    0 ... 1287 2200 5328]]


(6335, 20)

In [13]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100)) #Adding 100 lstm neurons in the layer
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [14]:
data['label'] = pd.factorize(data['label'])[0]
y = data['label']
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X_final,y_final, test_size=0.2, random_state=42)
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=8,batch_size=64)

Epoch 1/8
80/80 [==============================] - 7s 56ms/step - loss: 0.6399 - accuracy: 0.6352 - val_loss: 0.5446 - val_accuracy: 0.6898
Epoch 2/8
80/80 [==============================] - 5s 58ms/step - loss: 0.4095 - accuracy: 0.8169 - val_loss: 0.4664 - val_accuracy: 0.7782
Epoch 3/8
80/80 [==============================] - 3s 41ms/step - loss: 0.3066 - accuracy: 0.8731 - val_loss: 0.4891 - val_accuracy: 0.8019
Epoch 4/8
80/80 [==============================] - 4s 45ms/step - loss: 0.2445 - accuracy: 0.9025 - val_loss: 0.4808 - val_accuracy: 0.7853
Epoch 5/8
80/80 [==============================] - 3s 43ms/step - loss: 0.1960 - accuracy: 0.9225 - val_loss: 0.5479 - val_accuracy: 0.7932
Epoch 6/8
80/80 [==============================] - 3s 42ms/step - loss: 0.1583 - accuracy: 0.9402 - val_loss: 0.6061 - val_accuracy: 0.7861
Epoch 7/8
80/80 [==============================] - 4s 44ms/step - loss: 0.1421 - accuracy: 0.9449 - val_loss: 0.6404 - val_accuracy: 0.7837
Epoch 8/8
80/80 [===

In [16]:
y_pred=model.predict(X_test)
for i in range(0,np.shape(y_pred)[0]):
  if(y_pred[i]>0.5):
    y_pred[i]=1
  else:
    y_pred[i]=0
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7845303867403315

In [18]:
rev2 = []
for i in range(0,6335):
  new = re.sub('[^a-zA-Z]',' ',data['text'][i])
  new = new.lower()
  new = new.split()
  new = [ps.stem(word) for word in new if not word in set(sw)]
  new =  ' '.join(new)
  rev2.append(new)
rev2

['daniel greenfield shillman journal fellow freedom center new york writer focus radic islam final stretch elect hillari rodham clinton gone war fbi word unpreced thrown around often elect ought retir still unpreced nomine major polit parti go war fbi exactli hillari peopl done coma patient wake watch hour cnn hospit bed would assum fbi director jame comey hillari oppon elect fbi attack everyon obama cnn hillari peopl circul letter attack comey current media hit piec lambast target trump surpris clinton alli start run attack ad fbi fbi leadership warn entir left wing establish form lynch mob continu go hillari fbi credibl attack media democrat preemptiv head result investig clinton foundat hillari clinton covert struggl fbi agent obama doj peopl gone explos public new york time compar comey j edgar hoover bizarr headlin jame comey role recal hoover fbi fairli practic admit front spout nonsens boston globe publish column call comey resign outdon time editori claim scandal realli attack 

In [19]:
voc_size = 6000
onehot_repr=[one_hot(words,voc_size)for words in rev2]
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
np.shape(embedded_docs)

[[2629 3886 1759 ... 4862 3806 3134]
 [1002  731 1740 ... 5220 4550 4539]
 [2976 1767 1943 ... 4153 5384  833]
 ...
 [5319 3328 3208 ... 4461 5021 2052]
 [2668 2327 1621 ... 1931 3242 3623]
 [5354 2048 4064 ... 2200  612 1702]]


(6335, 20)

In [20]:
data['label'] = pd.factorize(data['label'])[0]
y = data['label']
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X_final,y_final, test_size=0.2, random_state=42)
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
80/80 [==============================] - 4s 47ms/step - loss: 0.6346 - accuracy: 0.7127 - val_loss: 0.4563 - val_accuracy: 0.7798
Epoch 2/10
80/80 [==============================] - 3s 41ms/step - loss: 0.3600 - accuracy: 0.8433 - val_loss: 0.4176 - val_accuracy: 0.7956
Epoch 3/10
80/80 [==============================] - 3s 42ms/step - loss: 0.2722 - accuracy: 0.8893 - val_loss: 0.4492 - val_accuracy: 0.7956
Epoch 4/10
80/80 [==============================] - 3s 40ms/step - loss: 0.2036 - accuracy: 0.9199 - val_loss: 0.4766 - val_accuracy: 0.8027
Epoch 5/10
80/80 [==============================] - 3s 41ms/step - loss: 0.1411 - accuracy: 0.9483 - val_loss: 0.5640 - val_accuracy: 0.8058
Epoch 6/10
80/80 [==============================] - 3s 37ms/step - loss: 0.1022 - accuracy: 0.9635 - val_loss: 0.6108 - val_accuracy: 0.8003
Epoch 7/10
80/80 [==============================] - 3s 40ms/step - loss: 0.0699 - accuracy: 0.9777 - val_loss: 0.7390 - val_accuracy: 0.7893
Epoch 8/10
80

In [22]:
y_pred=model.predict(X_test)
for i in range(0,np.shape(y_pred)[0]):
  if(y_pred[i]>0.5):
    y_pred[i]=1
  else:
    y_pred[i]=0
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [1.]], dtype=float32)

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7916337805840569